version: "3.7"

services:
  tkstats:
    build: .
    image: tkstats:latest
    environment:
      - DATABASE_FILE=/data/tkstats.db
    restart: always
    ports:
      - 127.0.0.1:3031:3031
    volumes:
      - ./tkstats.db:/data/tkstats.db

  updater:
    build:
      context: ./updater
    image: tkstats-updater:latest
    restart: always
    volumes:
      - ./tkstats.db:/data/tkstats.db
